---
output: 
  pdf_document:
#    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    template: ~/Dropbox/miscelanea/svm-r-markdown-templates/svm-latex-statement.tex
geometry: margin=1in
header-includes:
   - \linespread{1.05}

title: "Teaching Philosophy"
author: Steven V. Miller
affiliation: Department of Political Science, Clemson University
email: "svmille@clemson.edu"

fontfamily: mathpazo
fontsize: 11pt
---

My approach to teaching political science to students starts with an identification of a problem I see in the discipline in general. The gap between what political scientists do and what political scientists teach to students, certainly at the undergraduate-level, is becoming a chasm. Political scientists, especially quantitative political scientists in international relations, occupy their analytical energies with questions of data, measurement, rigorous formal models, and advanced statistical tools. While our discipline has evolved with (and has even been at the forefront of) advances in technology and inference, undergraduate curricula can be left unchanged. The same political science we learned as undergraduates decades ago may be what we teach our students. Many old concepts endure and should be taught, but the discipline has transformed. My teaching philosophy is motivated by a desire to bridge this gap by emphasizing the *science* of "political science." This approach has the benefit of bringing my in-class instruction in closer orbit of my research as well teaching students useful real-world knowledge and skills for jobs inside and outside academia, no matter the exact topic of the course. <!--% My seven years of teaching at the university-level has found this to be a rewarding experience for both the students -->

I begin every class with a discussion of science and inference. I find that most students are not accustomed to thinking of political science in this way, at least initially. After all, most students who enroll in political science as a major do so because they are interested in politics or think of themselves as political. This is even applicable to non-majors who enroll in introductory courses. Thus, they are unaccustomed to thinking about the science behind "political science" and do not see the connection between the two. I address this as soon as the class begins. 

For example, my introductory course on international relations, targeted for first-year students, starts with the important assumptions that underpin our means to inference. We start with an identification of the main actors we analyze (i.e. state leaders). We discuss the context of how state leaders interact in a strategic situation like the current discussions of nuclear proliferation involving the U.S. and Iran. This means we discuss some game theory, simple bargaining/ultimatum models, expected utility theory, and even go over how to read a regression table. This discussion happens before we start talking about topics like war, trade, or international environmental politics. In short, I spend the first few lectures of the semester teaching students how to evaluate claims about politics before we discuss the details of these topics in political science. Students must learn to think scientifically about the study of international relations before talking about international relations itself.

My upper-division international conflict course proceeds in a similar fashion. Students cannot take the upper-division conflict course without also taking the introductory course on international relations. However, I start with the same discussion. I tailor these first few weeks to reiterate bargaining models of conflict and expand on them for an audience largely comprised of juniors and seniors. I also bring in a discussion of terms like "conflict", "war", and "militarized interstate dispute (MID)." This amounts to a full week where we define these terms and narrow the scope in which we use them (e.g. wars are operationally MIDs in which more than a 1,000 troops die in combat). I build on this toward a simple "dangerous dyads" lecture that teaches students how to understand research design, data analysis, and importantly how to read and evaluate a regression table. This prepares the class for what is an article-heavy approach to understanding international conflict. I am a peace scientist by training and the class is replete with journal articles from our top general interest journals (e.g. *American Journal of Political Science*) and our top field journals (e.g. *International Studies Quarterly* and *Journal of Conflict Resolution*). I train students how to evaluate the results they read before we discuss the substance of the results themselves for understanding the causes of disputes and war.

<!-- My U.S. foreign policy course takes a similar approach even as the scope of the class changes. For example, my class on American foreign policy decision-making proceeds with a treatment of the prevailing theories of foreign policy decision-making and why American presidents make the decisions they make in foreign policy. I then apply these tools to an understanding of prominent cases like the Cuban Missile Crisis and Operation Eagle Claw during the Iran Hostage Crisis. What they first understood as just interesting events or American foreign policy episodes with normative implications, they soon see how we as researchers seek to understand these events and others scientifically. -->

My teaching philosophy makes every substantive course, in part, a methods/research design course in which we understand the assumptions that underpin our theoretical arguments and how the authors we read evaluate the support for the arguments they make. The quantitative methods class I teach simply extends this framework and, consistent with teaching philosophy, tailors it to applied political science research. This class covers the basics of measurement and descriptive statistics. It also discusses simple inferential tests, like differences in means. However, the class I teach gets the most mileage on regression itself. We do more than simple bivariate OLS in this class. Instead, we extend this framework quickly to include how to interpret interactions and what to do when the dependent variable we wish to explain is not drawn from a normal distribution (i.e. when the dependent variable is binary or ordinal). We even close with a discussion of reproducibility and transparency and mention why it is important consider a Bayesian framework for inference even if the latter topic is advanced and best saved for a special topics course in a methods sequence.

I approach political science instruction this way because I believe it is important to reconcile how political science is practiced by professionals and how it is taught to students. I also believe that this maximizes the student's learning experience when the student enrolled in political science expects just roundtable discussions of current events. My experience is that my students generally agree with this approach after the class has concluded. I score high in my ability to stimulate creative thinking. teach important principles, and impart factual knowledge. Those evaluations even played a role in my 2014 selection as one of the top 40 professors under the age of 40 who inspire their students.[^top40] Students are eager to rethink their previous understanding of politics after taking a class that teaches how to use the same rigorous inferential tools that academics use in their own research. 

[^top40]: http://newsstand.clemson.edu/mediarelations/two-clemson-professors-named-among-nations-top-40-under-40/

This experience I have at Clemson University is shared with experiences I had at previous jobs at the University of Alabama and the University of Illinois. Students have kept in touch and have tried to take other classes with me. It is always rewarding when students profess to retaining information from a class I taught a year or two prior.  It is even more rewarding when they say how my approach has helped them prepare for law school, business school, and even graduate school.

