---
output: 
  pdf_document:
#    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    template: ~/Dropbox/miscelanea/svm-r-markdown-templates/svm-latex-statement.tex
geometry: margin=1in
header-includes:
   - \linespread{1.05}

title: "Research Statement"
author: Steven V. Miller
affiliation: Department of Political Science, Clemson University
email: "svmille@clemson.edu"

fontfamily: mathpazo
fontsize: 11pt
---

My research clusters on two broad questions. First, how do contextual factors like external threat and conflict influence political attitudes, especially about the government? Second, how do we understand conflict as a process, more broadly? These two questions put my research agenda at the intersection of both the peace science community in international relations and political behavior scholars in comparative politics. These fields appear discrete from each other but my research shows how they overlap. My solo publications in outlets as diverse as *Political Behavior* and *Journal of Peace Research* highlight the potential to get both fields to learn from each other. My methodological approach toward answering these questions is similarly diverse, drawing on tools like mixed effects modeling of hundreds of thousands of individuals from cross-national survey data sets as well as estimating time-series-cross-sectional models of conflict onset and duration. I describe these two agendas in greater detail, outlining my focus, the finished products that have followed, and new research I am doing on these topics.[^others]

[^others]: [The research page on my website](http://svmiller.com/research/) contains links to additional projects on topics like gun control, human rights, and foreign aid that do not quite fit my overall research agendas. However, they have resulted in publications in *Social Science Quarterly* [on foreign aid](http://onlinelibrary.wiley.com/doi/10.1111/j.1540-6237.2012.00909.x/abstract) and [gun control](http://svmiller.com/research/what-americans-really-think-about-gun-control/), a few other working papers, and some media coverage in outlets like [*Bloomberg BusinessWeek*](https://www.bloomberg.com/news/articles/2017-10-11/the-bump-stock-millionaire-and-the-las-vegas-massacre), [*NBC News*](https://www.nbcnews.com/news/us-news/5-years-after-newtown-gun-control-groups-still-looking-big-n829871), and [*The Washington Post*](https://www.washingtonpost.com/news/wonk/wp/2017/10/02/experts-and-the-public-agree-on-how-to-stop-gun-violence-politicians-dont/?utm_term=.b5817be56247).

# How Do Conflict and Threat Influence Political Attitudes?

I am best known for my series of publications that explores how contextual factors external to the citizen and the state---like international conflict, terrorism, and even the economy---influence citizen attitudes. The political attitudes that interest me are multiple but I am most concerned in explaining attitudes about the authority the government should have. The attitudes I analyze are eclectic and the contextual factors on which I focus may vary but all my analyses share unifying assumptions that contextual factors of external threat, conflict, and macroeconomic downturns constitute a threat to material well-being and induce a sense of mortality. Individuals offset this sense of fear by looking to empower leadership with discretionary authority to provide for their welfare. This offsets the fear of mortality, consistent with insights from psychology, but it has important implications for democracy and our more general understanding of conflict processes.

This was the theme of my dissertation done under the direction of Douglas M. Gibler. My starting point was scholarship on territorial conflict, which the peace science community identified as a particularly salient issue disproportionately responsible for most of our disputes, wars, recurring conflicts, and international rivalries. Territorial conflict is even responsible for slowing democratic reforms and consolidating power in the executive. I argued that scholarship that identified disputed territory as a root cause of international conflict and a barrier to democratic reforms only captured part of the puzzle. Disputed territory changes political attitudes to favor international conflict and autocratic consolidation.

I have since published this dissertation in full. ["Individual-level Expectations of Executive Authority under Territorial Threat"](http://svmiller.com/research/individual-level-expectations-of-executive-authority-under-territorial-threat/), published in *Conflict Management and Peace Science*, provides the main argument that underpins the dissertation. I argue and show these territorial threats change citizen expectations of the power the executive should have, broadly changing citizen attitudes to favor rule of government by a "strong leader" unencumbered by legislative or electoral oversight. ["Territorial Disputes and the Politics of Individual Well-being"](http://svmiller.com/research/territorial-disputes-and-the-politics-of-individual-well-being/), published in *Journal of Peace Research*, shows that citizens targeted in a lot of territorial disputes think they have a lower quality of life but citizens in states that initiate a lot of territorial disputes are happier their government is taking efforts to secure the contested good. They report having a higher quality of life as a result. ["External Territorial Threats and Tolerance of Corruption: A Private/Government Distinction"](http://svmiller.com/research/external-territorial-threats-and-tolerance-of-corruption-a-privategovernment-distinction/) might be the most unique chapter from the dissertation. I leveraged three different cross-national data sets to show that territorial threat increases citizen attitudes to favor government corruption but decreases tolerance of corruption in society not involving government actors. This manuscript was recently published in *Peace Economics, Peace Science and Public Policy*.

I have three other publications that share this theme. ["Individual Identity Attachments and International Conflict: The Importance of Territorial Threat"](http://journals.sagepub.com/doi/full/10.1177/0010414012463899), co-authored with Douglas M. Gibler and Marc L. Hutchison in *Comparative Political Studies*, argues that territorial threat influences citizen-level identity attachments. We use Afrobarometer and World Values Survey data to show that citizens in states targeted by territorial threats are more likely to self-identify with their country whereas citizens in states that routinely initiate territorial revisions are more likely to self-identify with their ethnicity. Our within-case analysis of Nigeria demonstrates this spatial variation of identity attachments contingent on proximity to disputed territory. 

My other two publications in this research agenda are solo manuscripts that have already created considerable buzz in academic and pundit circles. ["Economic Threats or Societal Turmoil? Understanding Preferences for Authoritarian Political Systems"](http://svmiller.com/research/economic-threats-or-societal-turmoil-understanding-preferences-for-authoritarian-political-systems/), published in *Political Behavior*, contributes to the authoritarian governance literature by proposing both novel measures and formal arguments for why we should expect economic threats or societal conflict to lead to support for authoritarian governments. I find that it is mostly economic downturns that explain these changes in political attitudes, which has resulted in some [discussion from those interested in the problem of "democratic deconsolidation"](https://www.journalofdemocracy.org/sites/default/files/media/Journal%20of%20Democracy%20Web%20Exchange%20-%20Voeten_0.pdf) in the wake of the 2008-2009 financial crisis. ["The Effect of Terrorism on Judicial Confidence"](http://svmiller.com/research/effect-terrorism-judicial-confidence/), published in *Political Research Quarterly*, argues terrorism decreases support for judicial independence among countries with independent judiciaries because these important democratic institutions provide legal assurances to terror suspects. This paper is [often mentioned on Twitter](https://sage.altmetric.com/details/21397411) when, for example, President Trump tweets attacks against the legal system to promote counterterror measures he prefers.

I have several other working projects on this topic, some of which have already generated considerable publicity. ["White Outgroup Intolerance and Declining Support for American Democracy"](http://svmiller.com/research/white-outgroup-intolerance-democratic-support/), co-authored with Nicholas T. Davis, argues a relationship between whites who see ethnic/racial outgroups as status threats and support for authoritarian governance in the U.S. This paper has been featured in *The New York Times*, *NBC News*, *MacLeans*, *Rolling Stone*, and *ThinkProgress* among several other outlets. Other working papers and works in progress focus on how territorial threat influences different domestic political actors to prioritize defense spending and how pro-government violence increases support for authoritarian governments in Sub-Saharan Africa.

# How Do We Understand Conflict Processes?

I am a product of the peace science community, a collective of scholars who privilege advanced formal-theoretic and quantitative methods to understand the causes of militarized interstate disputes and the factors that influence the escalation of these disputes to war. My main research agenda has since evolved to explore the overlap of this field with comparative political behavior but my ongoing research still has plenty to contribute to the core mission of this community.

My first few publications sit firmly in this field of scholarship. I worked with Douglas M. Gibler to explore how the territorial conflict literature should encourage us to rethink what we know about the democratic peace. This resulted in two publications, one in [*Conflict Management and Peace Science* in 2011](http://cmp.sagepub.com/content/28/3/261) and another in [*Journal of Conflict Resolution* in 2013](http://jcr.sagepub.com/content/57/2/258.full), that show how territorial conflict conditions what we previously knew of how democracies peacefully settle their disputes and how well democracies are able to select cheap and quick disputes. Our collaboration resulted in another project, ["External Territorial Threat, State Capacity, and Civil War"](http://dmgibler.people.ua.edu/state-capacity.html), that shows how territorial threat increases state capacity and decreases the likelihood of a civil war over control of government. That was published in *Journal of Peace Research* in 2014.

My most recent contributions to this community focus on our conflict data. Douglas M. Gibler, Erin K. Little, and I published a revised version of the Correlates of War (CoW) Militarized Interstate Dispute (MID) data set [in *International Studies Quarterly*](https://academic.oup.com/isq/article-abstract/60/4/719/2918882/An-Analysis-of-the-Militarized-Interstate-Dispute?redirectedFrom=fulltext). We show an error rate of more than 72% to version 4.01 of the MID data and our revisions, which we call the [GML MID data](http://svmiller.com/gml-mid-data/) and host on my website, have important implications for some of our most prominent works that used the CoW-MID data. The results of this project, which we have been doing together since 2009, led Gibler and I to rethink conflict as a process to focus less on incidents and more on the demands that states communicate to each other over some issue. This project, titled ["What Do Leaders Want? Collecting and Coding Issue Positions and Demands in the Militarized Interstate Dispute (MID) Data, 1816-2010"](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1729138&HistoricalAwards=false), resulted in external funding from the National Science Foundation (NSF) worth $92,787 for Clemson University.

Curating our GML MID data and my NSF grant will consume my analytical energies for the research I do on this topic. However, I do have a few other works in progress that answer research questions of interest to the peace science community. The first project, tentatively titled "When and Where is the Democratic Peace?", works with two graduate students in the Clemson University Department of Mathematical Sciences to estimate a mixed effects time-series-cross-sectional model with spike-and-slab priors to assess the scope of when (i.e. time periods) and where (i.e. dyads and regions) we can attribute a causal relationship between increasing democracy and the absence of MIDs. I have tentative follow-up plans to follow this model with another that assesses John Vasquez' "steps to war" argument by region and temporal domain, identifying when and where disputed territory was more likely to escalate to war.


<!-- My primary research agenda focuses on the relationship between external threat and political attitudes, cutting at intersections between traditional international relations and comparative political behavior. How do external threats to the state influence the attitudes and behavior of the state's citizens?  We know that certain types of external threats, namely threats to the territorial integrity of the state, are salient threats in international politics. Its association with all forms of inter-state conflict is robust. However, these external threats do more than explain patterns of conflict and conflict processes between states. These external treats influence domestic politics of the state.

My research unpacks how external threats influence a state's domestic politics. Though my research has included a focus on domestic political institutions, my primary focus is on the political attitudes and behavior of ordinary citizens. I do this because the role of the citizen in conflict processes has gone mostly unaddressed. Assumptions about individual-level attitudes inform much of the extant territorial conflict scholarship, though little exists assessing the full extent to which external threats influence political attitudes and behavior. My research does this and illustrates what it means for conflict processes between states. 

I describe my research agenda below in greater detail. I focus first on the projects most related to my primary research agenda before discussing other projects that have been completed or are ongoing but constitute a different research focus.

# Territorial Threat and Political Attitudes

My research agenda on the connection between territorial threat and political attitudes has produced two publications and two finished manuscripts currently under review. As I elaborate here, my research demonstrates the pervasive effect of territorial threat on multiple, seemingly unrelated, political attitudes in countries across the globe. In short, my research underscores the wide-reaching salience of territorial threats on the attitudes and behavior of citizens.

In "Territorial Disputes and the Politics of Individual Well-Being" (published at *Journal of Peace Research* in 2013), I analyze how territorial disputes affect the quality of life for individuals.  Citizens in states that are frequently targeted in territorial disputes by a revisionist neighbor live in a political climate characterized by constant threat and militarization. It is unsurprising that a general malaise and unhappiness follows conditions of territorial threat. However, I also demonstrate that states that initiate territorial revisions against neighbors tend to have citizens who are happier. The initiation of a dispute satisfies key interest groups formed around the territory and diversionary logic suggests that the symbolic qualities of the territory are important to all citizens. These citizens will be satisfied that the state leader is taking aggressive measures to secure the territorial good. Citizens are happier for it and state leaders, eager to please their constituents, are willing to initiate territorial revisions against neighbors. Using mixed effects modeling of World Values Survey data and a case study of Nigeria, my research demonstrates that conflict processes are different for initiators and targets at the individual-level, not just at the level of conflict between states.

In "Individual Identity Attachments and International Conflict: The Importance of Territorial Threat" (published at *Comparative Political Studies* in 2012), my research (with Douglas M. Gibler and Marc L. Hutchison) demonstrates that conflict processes between states over territory are not uniform across targets and initiators. Citizens in states that are subject to territorial revisions from another state are more likely to self-identify as members of their country (a "rally `round the flag effect"). By contrast, citizens in states that initiate territorial revisions are more likely to identify as members of their ethnicity. This is because the process of selling the initiation of a territorial conflict requires selling it as an ethnic issue and mobilizing opinion along ethnic lines. Using Afrobarometer and World Values Survey data, we find this distinction in individual-level identity attachments. Further, we use another case study of Nigeria to demonstrate the spatial variation of identity attachments within one country contingent on proximity to disputed territory.

"Individual-Level Expectations of Executive Authority: The Importance of Territorial Threat" was part of my dissertation and is forthcoming at *Conflict Management and Peace Science*. This manuscript addresses a discrepancy in our understanding of the effect of territorial threat on domestic political processes. Around the globe, democratization efforts have stalled and power is being concentrated in state leaders that enjoy measurable support and approval. Why? I argue that citizens in states under territorial threat look to the state leader to provide for their security. Thus, they want to embolden executive authority to provide for their security without interference of electoral constraints or legislative oversight. I demonstrate this using two waves of World Values Survey data and latent variable modeling of territorial threat. Consistent with authoritarian values research, I find that territorial threat produces a convergence of opinion between authoritarians and non-authoritarians in support of strong leaders.

"External Territorial Threats and Tolerance of Corruption: A Private/Government Distinction" offers a novel argument to two interesting questions in the corruption literature. Can citizens perceive corruption but tolerate it? Corruption research tends to conflate corruption perception as corruption tolerance. Though it is intuitive that these two are related, they are ultimately separable concepts. Further, can citizens condone government corruption but condemn corruption not involving the national government? Extant corruption research has not discerned the important difference between the two. I propose an answer to both by reference to the territorial conflict literature. When citizens value their security as the highest government priority, they are more likely to condone corrupt behavior elsewhere provided their security is provided. However, citizens who cleave together as a show of resolve against the rival are unlikely to tolerate corrupt behavior among themselves since this behavior is interpreting as deviating from group norms. I demonstrate this using mixed effects modeling of corruption attitudes across three distinct cross-national survey data sets. This manuscript is currently under review at *British Journal of Political Science*.

# Other Research Agendas

While my research focus is mostly at the intersection between territorial conflict and comparative political behavior, I do have other ongoing research agendas and have published on a diverse array of topics.

Some of my earliest research with Douglas M. Gibler challenged received wisdom from democratic peace research. If the relationship and causal arrow between joint democracy and peace is spurious to the presence or absence of territorial conflict, then the so-called auxiliary hypotheses of democratic peace are spurious as well.<!-- \footnote{See Douglas M. Gibler, *The Territorial Peace} (Cambridge University Press, 2012).}  My research (with Douglas M. Gibler) finds this to be the case. In "Democracies, Territory and Negotiated Compromises" (published at *Conflict Management and Peace Science* in 2011), we find that democracies are no different from other types of states in their conflict management patterns when territorial threat is also considered. Disputes involving two democracies are no more or less likely to peacefully settle their disputes. In "Quick Victories? Territory, Democracies and Their Disputes" (published at *Journal of Conflict Resolution* in 2013), we find that the purported conflict-selection advantages democracies are thought to enjoy are also epiphenomenal to territorial issues. This research is a direct challenge to wisdom received from the democratic peace, purported to be one of the most important and most robust findings in the discipline.

Douglas M. Gibler, Erin K. Little, and I are also working on finalizing a project of considerable importance to the study of international conflict. Over a five-year period from 2009 to 2014, I worked on a project that evaluated the Correlates of War Militarized Interstate Dispute (CoW-MID) for errors and inconsistencies. CoW-MID was released in its modern form in 1996 and was last updated in 2004 before a 2014 update extended the data from 1816 to 2010. However, the heart of the data set lay in earlier codings of disputes from 1816 to 1992 (and later 2001). Our contention was that better access to primary sources and secondary sources made possible by advances in technology would lead to a considerable re-evaluation of CoW-MID, the most widely used conflict data set in the discipline. In a manuscript in preparation titled "An Evaluation of the MID Dataset, 1816-2001", we report our findings of an error rate of half the original data and discuss the implications of our findings for conflict scholarship that relies on this data set. This manuscript is currently forthcoming at *International Studies Quarterly*.

I am also engaging in research on the politics of foreign aid allocation in the United States. Foreign aid is an important policy instrument for the United States, which hopes to use its position as the single largest foreign aid donor in the world to achieve security objectives. How exactly does the U.S. distribute foreign aid? Is the provision of aid a proverbial "carrot" or the rescinding of aid a "stick"? In an ongoing project tentatively titled "Understanding Carrots and Sticks in U.S. Aid Allocation: The Case of the Middle East", I use the case of Israeli terror threats in the United States to find that foreign aid is mostly a stick. Using mixed effects modeling of U.S. economic aid and foreign aid provisions to the Middle East from 1968 to 2012, I find the U.S. is more likely to withhold aid to the region in general when Israel is subject to greater terror threats. However, even this is unequally applied. Countries like Iraq, Sudan, and Libya are punished further as a result of increasing terror threats against Israel while Turkey and Tunisia are rewarded. This project complements well "Comparing the Foreign Aid Policies of Presidents Bush and Obama" (published with Douglas M. Gibler in *Social Science Quarterly* in 2012), which analyzes similarities between George W. Bush and Barack Obama in the use of foreign aid as an American policy instrument around the world.

Another project, titled "Economic Threats or Societal Turmoil? Understanding Preferences for Authoritarian Political Systems" generalizes my other manuscript on the effect of territorial threat on support for authoritarian state leaders. One longstanding source of uncertainty about the emergence and popularity of authoritarian leaders in places like Russia draws attention the economic and social conditions. When the economy is under considerable duress or when society at large is in turmoil, individuals are thought to want and support strong authoritarian leaders that provide for their security in prominent cases like Russia. However, there is a problem of collinearity in exceptional cases like this. Both coincide. I offer clarity on support for strong leaders by looking at individual-level preferences for these strong leaders. I find that it is mostly economic factors that lead to this popular support for strong leaders. This manuscript is nearing completion and is ready to be sent for review.

<!-- My primary research agenda explores how threats to national security and prosperity change individual-level political attitudes to favor authoritarian governments and bellicose foreign policies that lead countries to war. Most political science scholarship conforms to conventional wisdom when it argues these policies are initiated by opportunistic political elites and government leaders, leaving the general public in the role of helpless bystander for policies they ultimately do not want. My research challenges this conventional wisdom. I show how external security threats lead citizens to prefer centralized executive authority and aggressive foreign policies. My research helps us explain the incidence of authoritarian governments and militarized conflict around the world.

My classification of external security threats is generalizable and considers multiple forms of security threats, but I give special attention to territorial threats. These are a class of foreign policy issues that are peculiar in their relationship with all forms of militarized conflict. More wars have been fought over the distribution of territory between countries than over any other issue. My individual research shows how these territorial threats lead citizens across the world to identify with their national government, to support state leaders to provide for their well-being, to prefer heads of state that rule by discretion, and to empower those state leaders to engage in corruption. <!-- Additional working papers show this class of threat is unique in explaining outcomes like these. 

My research has been published in top journals of international relations, like *International Studies Quarterly*, *Journal of Peace Research*, and several other peer-reviewed outlets. It has also attracted some media attention with appearances in, among other outlets, *The Washington Post* (http://wpo.st/n2bI1) and a forthcoming appearance in *Maclean's Magazine*, a leading current events magazine in Canada, to discuss my research on authoritarian preferences. My curriculum vitae contains additional information about these research projects.-->
